name: Django CI/CD Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh-key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
#        key: ${{secrets.KEY}}
        script: |
          cd /var/www/tasks_cicd/project_asca/backend
          git pull
          systemctl restart gunicorn.service
          systemctl reload nginx.service
            
          whoami



